import { parseProducts } from '../utils/utils.js'

const rawData = {
  Max: 10,
  Offset: 0,
  count: 10,
  data: [
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 82060207,
      image: 'ab112989-3514-4ab0-a5d8-d9bfb38bea6f.jpg',
      index: 1,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Galletitas Carrefour pepas tricolor 170 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 109,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 6
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224141,
      image: '0cbadb05-1790-4247-bb01-3b9e056330c1.jpg',
      index: 2,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Alcohol sanitizante Carrefour al 70% 500 cc.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 423,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 3
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224632,
      image: '8514ee4c-d46a-4eea-8368-ad4e199754e5.jpg',
      index: 3,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Chocolate Carrefour en rama surtido 100 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 369,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 2
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88223884,
      image: '69944b7a-4acc-49b9-88f5-bc268dd4e8fd.jpg',
      index: 4,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Repelente spray Carrefour extra duración 200 cc.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 519,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 21
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224451,
      image: '86bb4edd-ffa6-49b7-aa5a-a94eab4a8c43.jpg',
      index: 5,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Algodón plegado Carrefour 400 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 812,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 2
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224568,
      image: '3f40bfc7-531d-4a70-8f2c-8395a032cf56.jpg',
      index: 6,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Hamburguesa Huella Natural 4 u.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 857,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 7
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224515,
      image: 'cf470774-4561-4476-8cc6-a81c292a6118.jpg',
      index: 7,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Budín Carrefour limón 220 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 234,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 1
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88223902,
      image: 'a777341c-9bb3-49ac-9b7c-5de11bbd4aa2.jpg',
      index: 8,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Sardinas en salsa de tomate Carrefour 160 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 389,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 3
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '8',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224570,
      image: '6fbdff3d-ef19-4b9f-8530-28b309ff45d0.jpg',
      index: 9,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Colonia Carrefour clásica 500 cc.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 492,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 6
    },
    {
      applyDiscount: false,
      campaignTags: null,
      campaigns: null,
      contentQuantity: 0,
      description: '',
      enabled: true,
      entityName: '',
      gtin: '',
      hasCustomPhoto: false,
      hasDeliveryFee: false,
      hidesPrice: false,
      id: 88224883,
      image: 'fcd7e699-c507-4495-b20d-dd523f536c78.jpg',
      index: 10,
      infoLabels: null,
      integrationCode: '',
      isDeleted: false,
      isPremiumPlacement: false,
      isPriceFrom: false,
      maxQuantity: 0,
      measurementUnit: null,
      menuId: 0,
      name: 'Milanesa rebozada Huella Natural carne 500 g.',
      ncrStatus: '',
      oneClickEnabled: true,
      pill: null,
      prescriptionBehavior: 'NO',
      price: 805,
      pricePerMeasurementUnit: 0,
      rating: 0,
      requiresAgeCheck: false,
      score: 0,
      sectionId: 4317970,
      shippingAmountDiscountPercentage: 0,
      stock: 2
    }
  ],
  total: 11
}

const getProductsOfCategoryData = () => {
  const marketName = 'Carrefour - Market Carapachay (201)'
  const categoryName = 'Aceites'
  const products = parseProducts(rawData.data)

  const category = {
    name: marketName,
    category: {
      name: categoryName,
      products
    }
  }

  return category
}

export { getProductsOfCategoryData }
