name: "Scrape"

on: workflow_dispatch

permissions:
  contents: write

jobs:
  scrape1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright system deps + browsers
        run: npx playwright install --with-deps

      - name: Run scrape
        run: pnpm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_1 }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[bot] Update PedidosYa scraper database"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git --force

  scrape2:
    needs: scrape1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright system deps + browsers
        run: npx playwright install --with-deps

      - name: Pull latest
        run: git pull

      - name: Run scrape
        run: pnpm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_2 }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git --force

  scrape3:
    needs: scrape2
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright system deps + browsers
        run: npx playwright install --with-deps

      - name: Pull latest
        run: git pull

      - name: Run scrape
        run: pnpm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_3 }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git --force