name: "Scrape"

on: workflow_dispatch

jobs:
  scrape1:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
          run_install: false

      - name: Install dependencies (including devDependencies)
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run scrape
        run: npm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_1 }}

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[bot] Update PedidosYa scraper database"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git

  scrape2:
    needs: scrape1
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
          run_install: false

      - name: Install dependencies (including devDependencies)
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Pull
        run: git pull

      - name: Run scrape
        run: npm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_2 }}

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git --force

  scrape3:
    needs: scrape2
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
          run_install: false

      - name: Install dependencies (including devDependencies)
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Pull
        run: git pull

      - name: Run scrape
        run: npm run scrape
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PEDIDOSYA_IMG_BASE_URL: ${{ vars.PEDIDOSYA_IMG_BASE_URL }}
          PEDIDOSYA_CATEGORY_URL: ${{ vars.PEDIDOSYA_CATEGORY_URL }}
          PEDIDOSYA_PRODUCT_URL: ${{ vars.PEDIDOSYA_PRODUCT_URL }}
          DATA_MARKETS: ${{ vars.DATA_MARKETS_3 }}

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/whoknowsi/pedidosya-scraper-api.git --force